name: site_monitoring
description: A sample command-line application.
version: 1.0.0
repository: https://github.com/maxiakalimit/site_monitoring

environment:
  sdk: ^3.0.3

dependencies:
  http: ^1.1.0
  path:
  l: ^4.0.2
  args:
dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
